

% PES_e = (5E-2*xe_axis.^2) + (5E-2*xn_aux.^2) + lambda*(xe_axis.*xn_aux);
% PES_n = (5E-2*xe_aux.^2) + (5E-2*xn_axis.^2) + lambda*(xe_aux.*xn_axis);


PES_e = 1./abs(xn_aux - R_0) + 1./abs(xn_aux - R_2) ...
    - (error_function_over_r(full(abs(xe_axis - R_0)),R_c_fixed_l) ...
    + error_function_over_r(full(abs(xe_axis - R_2)),R_c_fixed_r) ...
    + error_function_over_r(full(abs(xe_axis - xn_aux)),R_c));

PES_n = 1./abs(xn_axis - R_0) + 1./abs(xn_axis - R_2) ...
    - (error_function_over_r(full(abs(xe_aux - R_0)),R_c_fixed_l) ...
    + error_function_over_r(full(abs(xe_aux - R_2)),R_c_fixed_r) ...
    + error_function_over_r(full(abs(xe_aux - xn_axis)),R_c));